from setuptools import setup

setup(
    name = 'Pillow-PIL',
    version = '0.1dev',
    description = 'Pillow wrapper for PIL compatibility',
    author = 'Yin Peng',
    author_email = 'yinpeng99@gmail.com',
    url = 'https://github.com/yinpeng/pillow-pil',
    package_dir = {'':'PillowPIL'},
    py_modules = [
        'ArgImagePlugin',
        'BdfFontFile',
        'BmpImagePlugin',
        'BufrStubImagePlugin',
        'ContainerIO',
        'CurImagePlugin',
        'DcxImagePlugin',
        'EpsImagePlugin',
        'ExifTags',
        'FitsStubImagePlugin',
        'FliImagePlugin',
        'FontFile',
        'FpxImagePlugin',
        'GbrImagePlugin',
        'GdImageFile',
        'GifImagePlugin',
        'GimpGradientFile',
        'GimpPaletteFile',
        'GribStubImagePlugin',
        'Hdf5StubImagePlugin',
        'IcnsImagePlugin',
        'IcoImagePlugin',
        'ImageChops',
        'ImageCms',
        'ImageColor',
        'ImageDraw2',
        'ImageDraw',
        'ImageEnhance',
        'ImageFileIO',
        'ImageFile',
        'ImageFilter',
        'ImageFont',
        'ImageGL',
        'ImageGrab',
        'ImageMath',
        'ImageMode',
        'ImageOps',
        'ImagePalette',
        'ImagePath',
        'Image',
        'ImageQt',
        'ImageSequence',
        'ImageShow',
        'ImageStat',
        'ImageTk',
        'ImageTransform',
        'ImageWin',
        'ImImagePlugin',
        'ImtImagePlugin',
        'IptcImagePlugin',
        'JpegImagePlugin',
        'McIdasImagePlugin',
        'MicImagePlugin',
        'MpegImagePlugin',
        'MspImagePlugin',
        'OleFileIO',
        'PaletteFile',
        'PalmImagePlugin',
        'PcdImagePlugin',
        'PcfFontFile',
        'PcxImagePlugin',
        'PdfImagePlugin',
        'PixarImagePlugin',
        'PngImagePlugin',
        'PpmImagePlugin',
        'PsdImagePlugin',
        'PSDraw',
        'SgiImagePlugin',
        'SpiderImagePlugin',
        'SunImagePlugin',
        'TarIO',
        'TgaImagePlugin',
        'TiffImagePlugin',
        'TiffTags',
        'WalImageFile',
        'WmfImagePlugin',
        'XbmImagePlugin',
        'XpmImagePlugin',
        'XVThumbImagePlugin',
        ],
    install_requires = [
        'Pillow',
        ],
)
